version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak-demo-postgres-for-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-26-1-3
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: keycloak-demo-backend
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5000"
      Keycloak__BaseUrl: http://keycloak:8080
      Keycloak__Realm: demo-realm
      CORS__AllowedOrigins: "http://localhost:5173"
    networks:
      - keycloak-network
    depends_on:
      - keycloak
  # Frontend Vue app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: keycloak-demo-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:5000/api
      - VITE_KEYCLOAK_URL=http://keycloak:8080
      - VITE_KEYCLOAK_REALM=demo-realm
      - VITE_KEYCLOAK_CLIENT_ID=frontend-client
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - keycloak-network
    depends_on:
      - backend

networks:
  keycloak-network:
    name: keycloak-network

volumes:
  postgres_data:
